# Generated by Django 6.0.7 on 2026-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_status_job_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
    ]
