# Generated by Django 6.0.7 on 2026-07-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
