# Generated by Django 6.0.7 on 2026-07-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_education_resume_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
